### ISSUE TITLE
Error in `v6.1.1`

### ISSUE THREAD

**Issue by vanthiyathevan** [mdreizin/webpack-config#34]
Hello,
I updated to `v6.1.1`. Getting this error. I managed to track down to the `ConfigMergeCommand` not resolving extend path `/home/mohan/vc-portal/client/webpack.config.[env].js'`

```
/home/mohan/project/vc-portal/node_modules/webpack-config/dist/Config.js:101
        throw _iteratorError;
        ^

ReferenceError: name is not defined
    at eval (lodash.templateSources[5]:9:10)
    at ConfigPatternCache._eval (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/ConfigPatternCache.js:125:20)
    at ConfigNameResolver.resolve (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/ConfigNameResolver.js:98:32)
    at ConfigOptionsResolver.resolve (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/ConfigOptionsResolver.js:94:45)
    at ConfigMergeCommand.execute (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/ConfigMergeCommand.js:59:46)
    at executeCommand (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/Config.js:89:15)
    at Config.merge (/home/mohan/project/vc-portal/node_modules/webpack-config/dist/Config.js:198:29)
    at Object.<anonymous> (webpack.config.base.js:119:29)
    at Module._compile (module.js:541:32)
    at loader (/home/mohan/project/vc-portal/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mohan/project/vc-portal/node_modules/babel-register/lib/node.js:158:7)

```

**Comment by mdreizin** [comment]
@vanthiyathevan Please look at [changelog](https://github.com/mdreizin/webpack-config/wiki/Changelog#v600).

**Comment by mdreizin** [comment]
@vanthiyathevan I'm sorry, but you need to do some migration steps.

**Comment by mdreizin** [comment]
@vanthiyathevan Could you please share your config if it is possible?

**Comment by vanthiyathevan** [comment]
@mdreizin Thanks for the quick response. 
I've already made the migration step changes. This works in `v6.0.0`. 
```
node -v v6.3.0
```
here are the [config files](https://gist.github.com/vanthiyathevan/34ba3d4cbd52d4ff134d7f35b141de4b)

**Comment by mdreizin** [comment]
@vanthiyathevan Thanks a lot. I have just commented gist.

**Comment by mdreizin** [comment]
@vanthiyathevan I have reproduced locally. Working on fix.

**Comment by mdreizin** [comment]
@vanthiyathevan Thanks again for reporting. Please update to `6.1.2`.

**Comment by mdreizin** [comment]
@vanthiyathevan https://travis-ci.org/mdreizin/webpack-config/builds/150677104

**Comment by vanthiyathevan** [comment]
Thank you for the fast response and fix.

**Comment by mdreizin** [comment]
@vanthiyathevan Welcome. `6.1.2` version has been published to `npm`.

Let me know if it works for you. If everything is ok, please close this issue.

**Comment by vanthiyathevan** [comment]
Installed `6.1.2` and its working.
